//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\references\\Internal\\;D:\\references\\External\\")]
        public string BaseReferencePaths {
            get {
                return ((string)(this["BaseReferencePaths"]));
            }
            set {
                this["BaseReferencePaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\rufrt-vxbuild\\InternalReferences\\")]
        public string InternalReferencesSourcePath {
            get {
                return ((string)(this["InternalReferencesSourcePath"]));
            }
            set {
                this["InternalReferencesSourcePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\rufrt-vxbuild\\ExternalReferences\\")]
        public string ExternalReferencesSourcePath {
            get {
                return ((string)(this["ExternalReferencesSourcePath"]));
            }
            set {
                this["ExternalReferencesSourcePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\references\\Internal\\")]
        public string InternalReferencesTargetPath {
            get {
                return ((string)(this["InternalReferencesTargetPath"]));
            }
            set {
                this["InternalReferencesTargetPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\references\\External\\")]
        public string ExternalReferencesTargetPath {
            get {
                return ((string)(this["ExternalReferencesTargetPath"]));
            }
            set {
                this["ExternalReferencesTargetPath"] = value;
            }
        }
    }
}
