//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuruev.StyleCop.CSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuruev.StyleCop.CSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that your abbreviations string has wrong syntax.
        ///
        ///Please check that:
        ///- string literals don&apos;t contain any characters except UPPERCASE letters and digits
        ///- string literals are separated by whitespaces.
        /// </summary>
        internal static string AbbreviationsEditorWarning {
            get {
                return ResourceManager.GetString("AbbreviationsEditorWarning", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CapitalLetter {
            get {
                object obj = ResourceManager.GetObject("CapitalLetter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string CaptionInformation {
            get {
                return ResourceManager.GetString("CaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string CaptionWarning {
            get {
                return ResourceManager.GetString("CaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &quot;{0}&quot; Setting.
        /// </summary>
        internal static string CommonEditorCaption {
            get {
                return ResourceManager.GetString("CommonEditorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derived class.
        /// </summary>
        internal static string DerivedClassFriendlyName {
            get {
                return ResourceManager.GetString("DerivedClassFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...{0}.
        /// </summary>
        internal static string DerivingExample {
            get {
                return ResourceManager.GetString("DerivingExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that your derivings string has wrong syntax.
        ///
        ///Please check that:
        ///- string literals don&apos;t contain any characters except letters, digits and underscore
        ///- string literals are separated by whitespaces.
        /// </summary>
        internal static string DerivingsEditorWarning {
            get {
                return ResourceManager.GetString("DerivingsEditorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not check.
        /// </summary>
        internal static string DoNotCheck {
            get {
                return ResourceManager.GetString("DoNotCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string MacroAnyCode {
            get {
                return ResourceManager.GetString("MacroAnyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnyName_withoutRULES.
        /// </summary>
        internal static string MacroAnyDescription {
            get {
                return ResourceManager.GetString("MacroAnyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .*.
        /// </summary>
        internal static string MacroAnyRegular {
            get {
                return ResourceManager.GetString("MacroAnyRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string MacroAnySample {
            get {
                return ResourceManager.GetString("MacroAnySample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaBb.
        /// </summary>
        internal static string MacroCamelCode {
            get {
                return ResourceManager.GetString("MacroCamelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camelNamingStyle.
        /// </summary>
        internal static string MacroCamelDescription {
            get {
                return ResourceManager.GetString("MacroCamelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [a-z0-9]+(([A-Z0-9][a-z0-9]+){0})*.
        /// </summary>
        internal static string MacroCamelRegular {
            get {
                return ResourceManager.GetString("MacroCamelRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sampleName.
        /// </summary>
        internal static string MacroCamelSample {
            get {
                return ResourceManager.GetString("MacroCamelSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aa_Bb.
        /// </summary>
        internal static string MacroCapitalizedCode {
            get {
                return ResourceManager.GetString("MacroCapitalizedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All_Words_Capitalized.
        /// </summary>
        internal static string MacroCapitalizedDescription {
            get {
                return ResourceManager.GetString("MacroCapitalizedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (([A-Z0-9][a-z0-9]+){0})(_(([A-Z0-9][a-z0-9]+){0}))*.
        /// </summary>
        internal static string MacroCapitalizedRegular {
            get {
                return ResourceManager.GetString("MacroCapitalizedRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample_Name.
        /// </summary>
        internal static string MacroCapitalizedSample {
            get {
                return ResourceManager.GetString("MacroCapitalizedSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa_bb.
        /// </summary>
        internal static string MacroLowerCode {
            get {
                return ResourceManager.GetString("MacroLowerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all_words_lower.
        /// </summary>
        internal static string MacroLowerDescription {
            get {
                return ResourceManager.GetString("MacroLowerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [a-z0-9]+(_[a-z0-9]+)*.
        /// </summary>
        internal static string MacroLowerRegular {
            get {
                return ResourceManager.GetString("MacroLowerRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample_name.
        /// </summary>
        internal static string MacroLowerSample {
            get {
                return ResourceManager.GetString("MacroLowerSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AaBb.
        /// </summary>
        internal static string MacroPascalCode {
            get {
                return ResourceManager.GetString("MacroPascalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PascalNamingStyle.
        /// </summary>
        internal static string MacroPascalDescription {
            get {
                return ResourceManager.GetString("MacroPascalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (([A-Z0-9][a-z0-9]+){0})+.
        /// </summary>
        internal static string MacroPascalRegular {
            get {
                return ResourceManager.GetString("MacroPascalRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleName.
        /// </summary>
        internal static string MacroPascalSample {
            get {
                return ResourceManager.GetString("MacroPascalSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA_BB.
        /// </summary>
        internal static string MacroUpperCode {
            get {
                return ResourceManager.GetString("MacroUpperCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL_WORDS_UPPER.
        /// </summary>
        internal static string MacroUpperDescription {
            get {
                return ResourceManager.GetString("MacroUpperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A-Z0-9]+(_[A-Z0-9]+)*.
        /// </summary>
        internal static string MacroUpperRegular {
            get {
                return ResourceManager.GetString("MacroUpperRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAMPLE_NAME.
        /// </summary>
        internal static string MacroUpperSample {
            get {
                return ResourceManager.GetString("MacroUpperSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &quot;{0}&quot; Naming Rule.
        /// </summary>
        internal static string NamingRuleEditorCaption {
            get {
                return ResourceManager.GetString("NamingRuleEditorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that your rule definition string has wrong syntax.
        ///
        ///Please check that:
        ///- it doesn&apos;t contain whitespace characters
        ///- all macros are written correctly
        ///- string literals don&apos;t contain any characters except letters, digits and underscore
        ///- you are using &quot;Turn off&quot; option instead of empty definition.
        /// </summary>
        internal static string NamingRuleEditorWarning {
            get {
                return ResourceManager.GetString("NamingRuleEditorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to cancel all modification for this setting?
        ///
        ///It will be reset to its inherited (default) value:
        ///- {0}.
        /// </summary>
        internal static string ResetSettingQuestion {
            get {
                return ResourceManager.GetString("ResetSettingQuestion", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap RightArrow {
            get {
                object obj = ResourceManager.GetObject("RightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RuleDisabled {
            get {
                object obj = ResourceManager.GetObject("RuleDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RuleEnabled {
            get {
                object obj = ResourceManager.GetObject("RuleEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes a new instance..
        /// </summary>
        internal static string StandardConstructorSummaryText {
            get {
                return ResourceManager.GetString("StandardConstructorSummaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizes an instance..
        /// </summary>
        internal static string StandardDestructorSummaryText {
            get {
                return ResourceManager.GetString("StandardDestructorSummaryText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap StyleCopPlusLogo {
            get {
                object obj = ResourceManager.GetObject("StyleCopPlusLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StyleCopPlusTitle {
            get {
                object obj = ResourceManager.GetObject("StyleCopPlusTitle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
