//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuruev.StyleCop.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuruev.StyleCop.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region AdvancedNamingRules // Methods
        ///
        /////# [OK]
        /////# Method name is correct.
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	public class TestClass
        ///	{
        ///		public void TestMethod()
        ///		{
        ///		}
        ///	}
        ///}
        /////# [END]
        ///
        /////# [ERROR]
        /////# Method name is incorrect.
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	public class TestClass
        ///	{
        ///		public void Test_Method()
        ///		{
        ///		}
        ///	}
        ///}
        /////# [END]
        ///
        /////# [OK]
        /////# Test method names are correct.
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	public class TestClass
        ///	{
        ///		[TestMethod]
        ///		public void [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdvancedNamingRules {
            get {
                return ResourceManager.GetString("AdvancedNamingRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region ElementMustNotBeOnSingleLine // SP1502
        ///
        /////# [OK]
        /////# Well-formed example.
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	public class TestClass
        ///	{
        ///		public TestClass()
        ///		{
        ///		}
        ///	}
        ///}
        /////# [END]
        ///
        /////# [OK]
        /////# Special style for constructors.
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	public class TestClass
        ///	{
        ///		public TestClass()
        ///		{ }
        ///	}
        ///}
        /////# [END]
        ///
        /////# [OK]
        /////# Special style for constructors.
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	public class TestClass
        ///	{
        ///		public TestClass() { }
        ///	}
        ///}
        /////# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtendedOriginalRules {
            get {
                return ResourceManager.GetString("ExtendedOriginalRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region CodeLineMustNotEndWithWhitespace
        ///
        /////# [OK]
        /////# Source file is OK.
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	public class TestClass
        ///	{
        ///		public void TestMethod()
        ///		{
        ///			int a = 10;
        ///		}
        ///	}
        ///}
        /////# [END]
        ///
        /////# [OK]
        /////# Source file without a line break at the end.
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	public class TestClass
        ///	{
        ///		public void TestMethod()
        ///		{
        ///
        ///			int a = 10;
        ///		}
        ///	}
        ///}//# [END]
        ///
        /////# [ERROR]
        /////# There is excess whitespace at the end of the line.
        ///namespace Shuruev.StyleCop. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MoreCustomRules {
            get {
                return ResourceManager.GetString("MoreCustomRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //# [ERROR]
        /////# Public class doesn&apos;t have summary.
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	public class TestClass
        ///	{
        ///		public void TestMethod()
        ///		{
        ///			int a = 10;
        ///		}
        ///	}
        ///}
        /////# [ERROR]
        /////# Public method doesn&apos;t have summary.
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Hello there.
        ///	/// &lt;/summary&gt;
        ///	public class TestClass
        ///	{
        ///		public void TestMethod()
        ///		{
        ///			int a = 10;
        ///		}
        ///	}
        ///}
        /////# [OK]
        /////# Both class and method have summary.
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	/// &lt;summary&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SP1600 {
            get {
                return ResourceManager.GetString("SP1600", resourceCulture);
            }
        }
    }
}
