// <auto-generated />
using System;
using System.Collections.Generic;
using System.IO;

namespace ConsoleApplication1
{
	public class Class_1 : IDisposable
	{
		/// <summary>
		/// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
		/// </summary>
		void IDisposable.Dispose()
		{
			for (int i = 0; i < 10; i++)

			{
			}
		}
	}
}
