//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuruev.StyleCop.Test.CodeHelperTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Source {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Source() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuruev.StyleCop.Test.CodeHelperTests.Source.Source", typeof(Source).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.Threading;
        ///
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	public class Class1
        ///	{
        ///		private int m_field = 5;
        ///
        ///		public Class1()
        ///		{
        ///			try
        ///			{
        ///lab1:			m_field = 6;
        ///			}
        ///			catch (Exception ex)
        ///			{
        ///				throw;
        ///			}
        ///
        ///			for (int i = 0; i &lt; 10; i++)
        ///			{
        ///lab2:			m_field = 6;
        ///			}
        ///
        ///			foreach (string s in new[] { &quot;1&quot;, &quot;2&quot; })
        ///			{
        ///lab3:			m_field = 6;
        ///			}
        ///
        ///			using (MemoryStream ms = new MemoryStream())
        ///			{
        ///lab4:			m_field = 6;
        ///			}
        ///
        ///			goto  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.Threading;
        ///
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	public class Class1
        ///	{
        ///		private int m_field = 5;
        ///
        ///		public Class1()
        ///		{
        ///			try
        ///			{
        ///				int a1, a2 = 10, a3 = 20;
        ///				const int b1 = 30, b2 = 40;
        ///
        ///				m_field = 6;
        ///			}
        ///			catch (OutOfMemoryException ex1)
        ///			{
        ///				throw;
        ///			}
        ///			catch (Exception ex2)
        ///			{
        ///				throw;
        ///			}
        ///
        ///			for (int
        ///				i1,
        ///				i2 = 0,
        ///				i3 = 1;
        ///				i2 &lt; 10;
        ///				i2++)
        ///			for (int j1, j2 = 0,
        ///				j3 = 1;
        ///				j2 &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LocalDeclarations {
            get {
                return ResourceManager.GetString("LocalDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.Threading;
        ///
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	public class Class1
        ///	{
        ///		private int m_field = 5;
        ///
        ///		public Class1()
        ///		{
        ///			try
        ///			{
        ///lab1:			m_field = 6;
        ///			}
        ///			catch (Exception ex)
        ///			{
        ///				throw;
        ///			}
        ///
        ///			for (int i = 0; i &lt; 10; i++)
        ///			{
        ///lab2:			m_field = 6;
        ///			}
        ///
        ///			foreach (string s in new[] { &quot;1&quot;, &quot;2&quot; })
        ///			{
        ///lab3:			m_field = 6;
        ///			}
        ///
        ///			using (MemoryStream ms = new MemoryStream())
        ///			{
        ///lab4:			m_field = 6;
        ///			}
        ///
        ///			goto  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Shuruev.StyleCop.Test
        ///{
        ///	public class Class1
        ///	{
        ///		public void FalseMethodIsNotPrivate(object sender, EventArgs e)
        ///		{
        ///		}
        ///
        ///		private void FalseFirstArgumentIsNotObject(NotObject sender, EventArgs e)
        ///		{
        ///		}
        ///
        ///		private void FalseFirstArgumentHasWrongName(object notSender, EventArgs e)
        ///		{
        ///		}
        ///
        ///		private void FalseSecondArgumentIsNotEventArgs(object sender, EventArgsWrong e)
        ///		{
        ///		}
        ///
        ///		private void FalseSecondArgumentHasWrongName(object sender, EventArgs notE)
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivateEventHandlers {
            get {
                return ResourceManager.GetString("PrivateEventHandlers", resourceCulture);
            }
        }
    }
}
