namespace Microsoft.StyleCop.CSharp
{
    using Microsoft.StyleCop;
    using System;
    using System.Globalization;
    using System.Xml;

    public class FileHeader
    {
        private bool generated;
        private string headerText;
        private string headerXml;

        public FileHeader(string headerText)
        {
            Param.RequireNotNull(headerText, "headerText");
            this.headerText = headerText;
            try
            {
                if (this.headerText.Length > 0)
                {
                    this.headerXml = string.Format(CultureInfo.InvariantCulture, "<root>{0}</root>", new object[] { this.headerText });
                    XmlDocument document = new XmlDocument();
                    document.LoadXml(this.headerXml);
                    if (document.DocumentElement["autogenerated"] != null)
                    {
                        this.generated = true;
                    }
                    else if (document.DocumentElement["auto-generated"] != null)
                    {
                        this.generated = true;
                    }
                }
            }
            catch (XmlException)
            {
            }
        }

        public bool Generated
        {
            get
            {
                return this.generated;
            }
        }

        public string HeaderText
        {
            get
            {
                return this.headerText;
            }
        }

        public string HeaderXml
        {
            get
            {
                return this.headerXml;
            }
        }
    }
}

