namespace Microsoft.StyleCop.CSharp
{
    using System;
    using System.Diagnostics.CodeAnalysis;

    [SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Justification="Camel case better serves in this case.")]
    public enum CsTokenType
    {
        Abstract = 0x10,
        Add = 0x11,
        Alias = 0x12,
        As = 0x13,
        Ascending = 20,
        Attribute = 0x6d,
        AttributeColon = 11,
        Base = 0x15,
        BaseColon = 9,
        Break = 0x16,
        By = 0x17,
        Case = 0x18,
        Catch = 0x19,
        Checked = 0x1a,
        Class = 0x1b,
        CloseAttributeBracket = 0x6f,
        CloseCurlyBracket = 3,
        CloseGenericBracket = 7,
        CloseParenthesis = 1,
        CloseSquareBracket = 5,
        Comma = 13,
        Const = 0x1c,
        Continue = 0x1d,
        Default = 30,
        DefaultValue = 0x1f,
        Delegate = 0x20,
        Descending = 0x21,
        DestructorTilde = 0x72,
        Do = 0x22,
        Else = 0x23,
        EndOfLine = 0x67,
        Enum = 0x24,
        Equals = 0x25,
        Event = 0x26,
        Explicit = 0x27,
        Extern = 40,
        ExternDirective = 0x29,
        False = 0x2a,
        Finally = 0x2b,
        Fixed = 0x2c,
        For = 0x2d,
        Foreach = 0x2e,
        From = 0x2f,
        Get = 0x30,
        Goto = 0x31,
        Group = 50,
        If = 0x33,
        Implicit = 0x34,
        In = 0x35,
        Interface = 0x36,
        Internal = 0x37,
        Into = 0x38,
        Is = 0x39,
        Join = 0x3a,
        LabelColon = 12,
        Let = 0x3b,
        Lock = 60,
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId="MultiLine", Justification="Named to be consistent with casing of SingleLineComment."), SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId="Multi", Justification="Named to be consistent with casing of SingleLineComment.")]
        MultiLineComment = 0x6b,
        Namespace = 0x3d,
        New = 0x3e,
        Null = 0x3f,
        NullableTypeSymbol = 15,
        Number = 0x69,
        On = 0x40,
        OpenAttributeBracket = 110,
        OpenCurlyBracket = 2,
        OpenGenericBracket = 6,
        OpenParenthesis = 0,
        OpenSquareBracket = 4,
        Operator = 0x41,
        OperatorSymbol = 8,
        OrderBy = 0x42,
        Other = 0x65,
        Out = 0x43,
        Override = 0x44,
        Params = 0x45,
        Partial = 70,
        PreprocessorDirective = 0x6c,
        Private = 0x47,
        Protected = 0x48,
        Public = 0x49,
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId="Readonly", Justification="API has already been published and should not be changed.")]
        Readonly = 0x4a,
        Ref = 0x4b,
        Remove = 0x4c,
        Return = 0x4d,
        Sealed = 0x4e,
        Select = 0x4f,
        Semicolon = 14,
        Set = 80,
        SingleLineComment = 0x6a,
        Sizeof = 0x51,
        Stackalloc = 0x52,
        Static = 0x53,
        String = 0x68,
        Struct = 0x54,
        Switch = 0x55,
        This = 0x56,
        Throw = 0x57,
        True = 0x58,
        Try = 0x59,
        Typeof = 90,
        Unchecked = 0x5b,
        Unsafe = 0x5c,
        Using = 0x5d,
        UsingDirective = 0x5e,
        Virtual = 0x5f,
        Volatile = 0x60,
        Where = 0x61,
        WhereColon = 10,
        While = 0x62,
        WhileDo = 0x63,
        WhiteSpace = 0x66,
        XmlHeader = 0x70,
        XmlHeaderLine = 0x71,
        Yield = 100
    }
}

