//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelixBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelixBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS Attribute: {0}.
        /// </summary>
        internal static string DsAttribute {
            get {
                return ResourceManager.GetString("DsAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model ID: {0}.
        /// </summary>
        internal static string ModelId {
            get {
                return ResourceManager.GetString("ModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Line ID: {0}.
        /// </summary>
        internal static string ProductLineId {
            get {
                return ResourceManager.GetString("ProductLineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;
        ///	&lt;div class=&quot;Content Fourfold&quot;&gt;
        ///		&lt;div class=&quot;Text&quot;&gt;
        ///			This is a long, very long text. This is a long, very long text. This is a long,
        ///			very long text. This is a long, very long text. This is a long, very long text.&lt;/div&gt;
        ///	&lt;/div&gt;
        ///&lt;/td&gt;
        ///.
        /// </summary>
        internal static string RenderAttributes {
            get {
                return ResourceManager.GetString("RenderAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;
        ///	&lt;div class=&quot;Content Icon&quot;&gt;
        ///		&lt;img src=&quot;Images/funnel.png&quot; alt=&quot;Group&quot; /&gt;
        ///	&lt;/div&gt;
        ///&lt;/td&gt;
        ///&lt;td&gt;
        ///	&lt;div class=&quot;Content Fourfold&quot;&gt;
        ///		&lt;div class=&quot;Mark&quot;&gt;
        ///			{TYPE}&lt;/div&gt;
        ///		&lt;div class=&quot;Description&quot;&gt;
        ///			{RULES}&lt;/div&gt;
        ///	&lt;/div&gt;
        ///&lt;/td&gt;
        ///.
        /// </summary>
        internal static string RenderGroup {
            get {
                return ResourceManager.GetString("RenderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;
        ///	&lt;div class=&quot;Content&quot;&gt;
        ///		&lt;div class=&quot;Mark&quot;&gt;
        ///			{TYPE}&lt;/div&gt;
        ///		&lt;img
        ///			style=&quot;width: 50px; height: 37px;&quot;
        ///			src=&quot;{URL}&quot;
        ///			alt=&quot;Image&quot; /&gt;
        ///	&lt;/div&gt;
        ///&lt;/td&gt;
        ///.
        /// </summary>
        internal static string RenderImages {
            get {
                return ResourceManager.GetString("RenderImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;
        ///	&lt;div class=&quot;Content Icon&quot;&gt;
        ///		&lt;img src=&quot;Images/{ICON}&quot; alt=&quot;InfoNode&quot; /&gt;
        ///	&lt;/div&gt;
        ///&lt;/td&gt;
        ///&lt;td&gt;
        ///	&lt;div class=&quot;Content Double&quot;&gt;
        ///		&lt;div class=&quot;Mark&quot;&gt;
        ///			{TYPE}&lt;/div&gt;
        ///		&lt;div class=&quot;Title&quot;&gt;
        ///			&lt;b&gt;{TITLE}&lt;/b&gt;&lt;br /&gt;
        ///			{ID}&lt;br /&gt;
        ///		&lt;/div&gt;
        ///	&lt;/div&gt;
        ///&lt;/td&gt;
        ///.
        /// </summary>
        internal static string RenderInfoNode {
            get {
                return ResourceManager.GetString("RenderInfoNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;Item {CODE}&quot; {INDENT}&gt;
        ///	&lt;tr&gt;
        ///		{CONTENT}
        ///		{PROPERTIES}
        ///	&lt;/tr&gt;
        ///&lt;/table&gt;
        ///.
        /// </summary>
        internal static string RenderItem {
            get {
                return ResourceManager.GetString("RenderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;
        ///	&lt;div class=&quot;Content Triple&quot;&gt;
        ///		&lt;div class=&quot;Mark&quot;&gt;
        ///			SHORT {LANG}&lt;/div&gt;
        ///		&lt;div class=&quot;Text&quot;&gt;
        ///			{TEXT}&lt;/div&gt;
        ///	&lt;/div&gt;
        ///&lt;/td&gt;
        ///.
        /// </summary>
        internal static string RenderKeySellingPoints {
            get {
                return ResourceManager.GetString("RenderKeySellingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;
        ///	&lt;div class=&quot;Content Triple&quot;&gt;
        ///		&lt;div class=&quot;Mark&quot;&gt;
        ///			{LANG}&lt;/div&gt;
        ///		&lt;div class=&quot;Text&quot;&gt;
        ///			{TEXT}&lt;/div&gt;
        ///	&lt;/div&gt;
        ///&lt;/td&gt;
        ///.
        /// </summary>
        internal static string RenderMarketingDescription {
            get {
                return ResourceManager.GetString("RenderMarketingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;
        ///	&lt;div class=&quot;Content&quot;&gt;
        ///		&lt;div class=&quot;Mark&quot;&gt;
        ///			{TYPE} / {ANGLE}&lt;/div&gt;
        ///		&lt;img
        ///			style=&quot;width: 50px; height: 37px;&quot;
        ///			src=&quot;{URL}&quot;
        ///			alt=&quot;Image&quot; /&gt;
        ///	&lt;/div&gt;
        ///&lt;/td&gt;
        ///.
        /// </summary>
        internal static string RenderMultipleImages {
            get {
                return ResourceManager.GetString("RenderMultipleImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;
        ///	&lt;div class=&quot;Content Triple&quot;&gt;
        ///		&lt;div class=&quot;Mark&quot;&gt;
        ///			LONG {LANG}&lt;/div&gt;
        ///		&lt;div class=&quot;Text&quot;&gt;
        ///			{TEXT}&lt;/div&gt;
        ///	&lt;/div&gt;
        ///&lt;/td&gt;
        ///.
        /// </summary>
        internal static string RenderProductFeatures {
            get {
                return ResourceManager.GetString("RenderProductFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td class=&quot;Properties&quot;&gt;
        ///	&lt;div class=&quot;Template&quot;&gt;{TEMPLATE}&lt;/div&gt;
        ///	{ID}&lt;br /&gt;
        ///	{CREATED}&lt;br /&gt;
        ///	{UPDATED}&lt;br /&gt;
        ///	{OWNER}&lt;br /&gt;
        ///&lt;/td&gt;
        ///.
        /// </summary>
        internal static string RenderProperties {
            get {
                return ResourceManager.GetString("RenderProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU ID: {0}.
        /// </summary>
        internal static string SkuId {
            get {
                return ResourceManager.GetString("SkuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
